workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      vars:
        BUILD_TYPE: release
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com

  android-debug:
    name: Android Debug Workflow
    max_build_duration: 60
    environment:
      vars:
        BUILD_TYPE: debug
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
